Add flatmap prov information button
ABI-Software/flatmapvuer pull request #115
Opened 2023-08-11 04:06 UTC by Tehsurfer

2023-08-29 01:47 UTC, alan-wu commented on src/App.vue
> +      // console.log(taxon, id);
Can we keep the addMarker here please? It helps with checking rather the markers are working. Thanks.

2023-08-29 02:05 UTC, alan-wu requested changes
Thanks, it looks good and clean but there are few issues with the context cards

1. The banner image does not match the active species, perhaps the image can be removed.
2. I cannot hide the popup once is on display.
3. The "i" on the icon is transparent instead of solid white, it is not a big issue but it does not match with the others.

2023-08-29 22:11 UTC, Tehsurfer commented
I've implemented the feedback but am struggling with #3 as the icon is actually a font which is really hard to size. Have any ideas on how to make the background white?

2023-08-31 23:13 UTC, alan-wu approved these changes
Looks good, thanks.

2023-08-31 23:13 UTC, merged