Prov pop up feedback
ABI-Software/flatmapvuer pull request #97
Opened 2023-03-10 02:28 UTC by Tehsurfer

Origin, Destination, and Components titles now only show if data exists for them. 

'Search on components'  button now only shows if components have searchable data
![image](https://user-images.githubusercontent.com/37255664/224207615-cb7b6a35-7f90-4acf-a57d-ac7db2c51e36.png)

This is for these two wrike tickets:
https://www.wrike.com/open.htm?id=1068200377
https://www.wrike.com/open.htm?id=1068211673

2023-03-10 02:50 UTC, hsorby approved these changes

2023-03-10 02:59 UTC, Tehsurfer commented
Thanks Hugh

2023-03-12 22:00 UTC, alan-wu requested changes
Please take a look at the comments. Thanks.

2023-03-12 22:00 UTC, alan-wu commented on src/components/Tooltip.vue
> -        <div v-if="this.destinations" class="block">
Same as above.

2023-03-12 22:02 UTC, alan-wu commented
There is also another place that says this.destinations in the template and that should be updated as well.

2023-03-14 00:29 UTC, Tehsurfer commented
Oops sorry you are correct the 'this' should not be there

2023-03-14 01:18 UTC, alan-wu approved these changes

2023-03-14 01:18 UTC, merged